@startuml Hello World (v2 local)
'Copyright (c) 2026 Neil Piper (fork maintainer)
'Copyright (c) 2020 David Holsgrove
'SPDX-License-Identifier: MIT (For details, see https://github.com/npiper/gcp-icons-for-plantuml/blob/master/LICENSE-CODE)
!pragma svgparser sax
!include ../dist/GCPCommon.puml
!include ../dist/cloud_code.puml
!include ../dist/cloud_storage.puml

actor "Person" as personAlias
cloud_code(desktopAlias, "Label", "Technology", "Optional Description")
cloud_storage(storageAlias, "Label", "Technology", "Optional Description")

personAlias --> desktopAlias
desktopAlias --> storageAlias

@enduml
