@startuml Raw usage - Sprites (v2 local)
'Copyright (c) 2026 Neil Piper (fork maintainer)
'Copyright (c) 2020 David Holsgrove
'SPDX-License-Identifier: MIT (For details, see https://github.com/npiper/gcp-icons-for-plantuml/blob/master/LICENSE-CODE)
!pragma svgparser nano
!include ../dist/GCPCommon.puml
!include ../dist/ai_platform.puml
!include ../dist/iot_core.puml

component "<color:green><$ai_platform></color>" as myMLModel
database "<color:#232F3E><$iot_core></color>" as myRoboticService
iot_core(mySecondFunction, "Reinforcement Learning", "Gazebo")

rectangle "<color:GCP_SYMBOL_COLOR><$ai_platform></color>" as mySecondML

myMLModel --> myRoboticService
mySecondFunction --> mySecondML

@enduml
