@startuml Two Modes - Technical View (v2 local)
'Copyright (c) 2026 Neil Piper (fork maintainer)
'Copyright (c) 2020 David Holsgrove
'SPDX-License-Identifier: MIT (For details, see https://github.com/npiper/gcp-icons-for-plantuml/blob/master/LICENSE-CODE)
!pragma svgparser sax
!include ../dist/GCPCommon.puml
' Uncomment the following line to create simplified view
' !include ../dist/GCPSimplified.puml
!include ../dist/cloud_endpoints.puml
!include ../dist/app_engine.puml

' Include Material Design Common icons
!include <material/common>
!include <material/cellphone_android>

left to right direction

GCPEntityColoring(MA_CELLPHONE_ANDROID)
MA_CELLPHONE_ANDROID(#9E9E9E, 1, sources, rectangle, "Android")
cloud_endpoints(endpoints, "GCP Cloud Endpoints", "api")
app_engine(engine, "GCP App Engine", "API Backend Instances")

sources <--> endpoints
endpoints <--> engine

@enduml
