@startuml Two Modes - Simple View
!define GCPPuml https://raw.githubusercontent.com/npiper/gcp-icons-for-plantuml/refs/heads/feature/2026-update/dist
!includeurl GCPPuml/GCPCommon.puml
!includeurl GCPPuml/GCPSimplified.puml
!includeurl GCPPuml/cloud_endpoints.puml
!includeurl GCPPuml/app_engine.puml
!include <material/common>
!include <material/cellphone_android>

left to right direction
GCPEntityColoring(MA_CELLPHONE_ANDROID)
MA_CELLPHONE_ANDROID(#9E9E9E, 1, sources, rectangle, "Android")
cloud_endpoints(endpoints, "GCP Cloud Endpoints", "api")
app_engine(engine, "GCP App Engine", "API Backend Instances")

sources <--> endpoints
endpoints <--> engine
@enduml